/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardAddphotoRouteImport } from './routes/dashboard/addphoto'
import { Route as DashboardAddcardRouteImport } from './routes/dashboard/addcard'
import { Route as ApiUploadRouteImport } from './routes/api/upload'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAddphotoRoute = DashboardAddphotoRouteImport.update({
  id: '/addphoto',
  path: '/addphoto',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAddcardRoute = DashboardAddcardRouteImport.update({
  id: '/addcard',
  path: '/addcard',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/test': typeof TestRoute
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/addcard': typeof DashboardAddcardRoute
  '/dashboard/addphoto': typeof DashboardAddphotoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/test': typeof TestRoute
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/addcard': typeof DashboardAddcardRoute
  '/dashboard/addphoto': typeof DashboardAddphotoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/test': typeof TestRoute
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/addcard': typeof DashboardAddcardRoute
  '/dashboard/addphoto': typeof DashboardAddphotoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/test'
    | '/api/upload'
    | '/dashboard/addcard'
    | '/dashboard/addphoto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/test'
    | '/api/upload'
    | '/dashboard/addcard'
    | '/dashboard/addphoto'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/test'
    | '/api/upload'
    | '/dashboard/addcard'
    | '/dashboard/addphoto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  TestRoute: typeof TestRoute
  ApiUploadRoute: typeof ApiUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/addphoto': {
      id: '/dashboard/addphoto'
      path: '/addphoto'
      fullPath: '/dashboard/addphoto'
      preLoaderRoute: typeof DashboardAddphotoRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/addcard': {
      id: '/dashboard/addcard'
      path: '/addcard'
      fullPath: '/dashboard/addcard'
      preLoaderRoute: typeof DashboardAddcardRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAddcardRoute: typeof DashboardAddcardRoute
  DashboardAddphotoRoute: typeof DashboardAddphotoRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAddcardRoute: DashboardAddcardRoute,
  DashboardAddphotoRoute: DashboardAddphotoRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  TestRoute: TestRoute,
  ApiUploadRoute: ApiUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
