/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as TableRouteImport } from './routes/table'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FieldRouteImport } from './routes/field'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSellcardRouteImport } from './routes/dashboard/sellcard'
import { Route as DashboardPurchasehistoryRouteImport } from './routes/dashboard/purchasehistory'
import { Route as DashboardCardslistRouteImport } from './routes/dashboard/cardslist'
import { Route as DashboardAddphotoRouteImport } from './routes/dashboard/addphoto'
import { Route as DashboardAddcardRouteImport } from './routes/dashboard/addcard'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as DashboardEditpurchaseIdRouteImport } from './routes/dashboard/editpurchase/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRoute = FieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSellcardRoute = DashboardSellcardRouteImport.update({
  id: '/sellcard',
  path: '/sellcard',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPurchasehistoryRoute =
  DashboardPurchasehistoryRouteImport.update({
    id: '/purchasehistory',
    path: '/purchasehistory',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCardslistRoute = DashboardCardslistRouteImport.update({
  id: '/cardslist',
  path: '/cardslist',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAddphotoRoute = DashboardAddphotoRouteImport.update({
  id: '/addphoto',
  path: '/addphoto',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAddcardRoute = DashboardAddcardRouteImport.update({
  id: '/addcard',
  path: '/addcard',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEditpurchaseIdRoute = DashboardEditpurchaseIdRouteImport.update({
  id: '/editpurchase/$id',
  path: '/editpurchase/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/field': typeof FieldRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/table': typeof TableRoute
  '/test': typeof TestRoute
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/addcard': typeof DashboardAddcardRoute
  '/dashboard/addphoto': typeof DashboardAddphotoRoute
  '/dashboard/cardslist': typeof DashboardCardslistRoute
  '/dashboard/purchasehistory': typeof DashboardPurchasehistoryRoute
  '/dashboard/sellcard': typeof DashboardSellcardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/editpurchase/$id': typeof DashboardEditpurchaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/field': typeof FieldRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/table': typeof TableRoute
  '/test': typeof TestRoute
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/addcard': typeof DashboardAddcardRoute
  '/dashboard/addphoto': typeof DashboardAddphotoRoute
  '/dashboard/cardslist': typeof DashboardCardslistRoute
  '/dashboard/purchasehistory': typeof DashboardPurchasehistoryRoute
  '/dashboard/sellcard': typeof DashboardSellcardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/editpurchase/$id': typeof DashboardEditpurchaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/field': typeof FieldRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/table': typeof TableRoute
  '/test': typeof TestRoute
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/addcard': typeof DashboardAddcardRoute
  '/dashboard/addphoto': typeof DashboardAddphotoRoute
  '/dashboard/cardslist': typeof DashboardCardslistRoute
  '/dashboard/purchasehistory': typeof DashboardPurchasehistoryRoute
  '/dashboard/sellcard': typeof DashboardSellcardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/editpurchase/$id': typeof DashboardEditpurchaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/field'
    | '/login'
    | '/signup'
    | '/table'
    | '/test'
    | '/api/upload'
    | '/dashboard/addcard'
    | '/dashboard/addphoto'
    | '/dashboard/cardslist'
    | '/dashboard/purchasehistory'
    | '/dashboard/sellcard'
    | '/api/auth/$'
    | '/dashboard/editpurchase/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/field'
    | '/login'
    | '/signup'
    | '/table'
    | '/test'
    | '/api/upload'
    | '/dashboard/addcard'
    | '/dashboard/addphoto'
    | '/dashboard/cardslist'
    | '/dashboard/purchasehistory'
    | '/dashboard/sellcard'
    | '/api/auth/$'
    | '/dashboard/editpurchase/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/field'
    | '/login'
    | '/signup'
    | '/table'
    | '/test'
    | '/api/upload'
    | '/dashboard/addcard'
    | '/dashboard/addphoto'
    | '/dashboard/cardslist'
    | '/dashboard/purchasehistory'
    | '/dashboard/sellcard'
    | '/api/auth/$'
    | '/dashboard/editpurchase/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  FieldRoute: typeof FieldRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TableRoute: typeof TableRoute
  TestRoute: typeof TestRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field': {
      id: '/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sellcard': {
      id: '/dashboard/sellcard'
      path: '/sellcard'
      fullPath: '/dashboard/sellcard'
      preLoaderRoute: typeof DashboardSellcardRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/purchasehistory': {
      id: '/dashboard/purchasehistory'
      path: '/purchasehistory'
      fullPath: '/dashboard/purchasehistory'
      preLoaderRoute: typeof DashboardPurchasehistoryRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/cardslist': {
      id: '/dashboard/cardslist'
      path: '/cardslist'
      fullPath: '/dashboard/cardslist'
      preLoaderRoute: typeof DashboardCardslistRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/addphoto': {
      id: '/dashboard/addphoto'
      path: '/addphoto'
      fullPath: '/dashboard/addphoto'
      preLoaderRoute: typeof DashboardAddphotoRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/addcard': {
      id: '/dashboard/addcard'
      path: '/addcard'
      fullPath: '/dashboard/addcard'
      preLoaderRoute: typeof DashboardAddcardRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/editpurchase/$id': {
      id: '/dashboard/editpurchase/$id'
      path: '/editpurchase/$id'
      fullPath: '/dashboard/editpurchase/$id'
      preLoaderRoute: typeof DashboardEditpurchaseIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAddcardRoute: typeof DashboardAddcardRoute
  DashboardAddphotoRoute: typeof DashboardAddphotoRoute
  DashboardCardslistRoute: typeof DashboardCardslistRoute
  DashboardPurchasehistoryRoute: typeof DashboardPurchasehistoryRoute
  DashboardSellcardRoute: typeof DashboardSellcardRoute
  DashboardEditpurchaseIdRoute: typeof DashboardEditpurchaseIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAddcardRoute: DashboardAddcardRoute,
  DashboardAddphotoRoute: DashboardAddphotoRoute,
  DashboardCardslistRoute: DashboardCardslistRoute,
  DashboardPurchasehistoryRoute: DashboardPurchasehistoryRoute,
  DashboardSellcardRoute: DashboardSellcardRoute,
  DashboardEditpurchaseIdRoute: DashboardEditpurchaseIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  FieldRoute: FieldRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TableRoute: TableRoute,
  TestRoute: TestRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
